# These are supported funding model platforms

github: calipsow
buy_me_a_coffee: calipsow
thanks_dev: calipsow
custom: ['https://checkout.revolut.com/pay/ec9ec074-c38c-4ab0-8bfb-785e6a762fa6','https://donate.stripe.com/28odSy6WpdHr0IU6op']
